export default interface ApiData {
    reviewerId: string,
    reviewerName: string,
    reviewDesc: string,
    reviewContent: string,
    filmName: string,
    filmYear: string,
    reviewRating: number,
    filmURL: string,
    url: string,
    directors: Array<string>,
    images: Array<string>,
    datePublished: string,
    avatar: string,
};